[package]
name = "may_rpc_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
heck = "0.4"
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["extra-traits", "full"] }
